### ISSUE TITLE
AgentClinic-NEJM Data Release Inquiry

### ISSUE THREAD

**Issue by ttumyche** [SamuelSchmidgall/AgentClinic#2]
Appreciate your work!
As far as I know, AgentClinic-NEJM data has not been released yet.
Do you have any information on when it might be made available?

**Comment by SamuelSchmidgall** [comment]
Hello, thank you very much. Yes! I will make this available soon--I'll aim to get this incorporated by tomorrow.

**Comment by SamuelSchmidgall** [comment]
Hello, I have incorporated the new dataset and support for images in the latest update. Just let me know if you need anything else!

**Comment by ft2023** [comment]
Can you release larger-scale AgentClinic-NEJM data?

**Comment by SamuelSchmidgall** [comment]
Hello @ft2023. This is currently available by setting the keyword `agent_dataset=NEJM_Ext`. I've also made this more clear in the README. Let me know if you have any other questions.

**Comment by ft2023** [comment]
Do you mean the dataset contains 120 samples?

**Comment by ft2023** [comment]
Will you release collected 1k raw data from NEJM challenge cases?

**Comment by SamuelSchmidgall** [comment]
We will not be releasing the 1k raw data, but note that those are publicly available on the NEJM website for collection
