### ISSUE TITLE
Invitation to Explore Our Project ClinicalAgent and Collaborate

### ISSUE THREAD

**Issue by LeoYML** [SamuelSchmidgall/AgentClinic#3]
I am excited to discover the amazing project you have developed. Please feel free to visit our previously published paper, "ClinicalAgent: Clinical Trial Multi-Agent System with Large Language Model-based Reasoning" [https://arxiv.org/abs/2404.14777], which was published on April, 2024. We look forward to your suggestions and feedback. If you have any ideas and would like to collaborate with us, you are welcome.

**Comment by SamuelSchmidgall** [comment]
Thanks for sharing!!
